---
title: "Analyzed T cell transcriptomes of CAR-T cells generated by different transfections"
author: "Chentao LI"
date: "`r Sys.Date()`"
output: pdf_document
---

# Data loading
## import packages
```{r,message=F,warning=F}
gc()
memory.limit(10240000000)
library(Seurat)
library(SeuratObject)
library(tidyverse)
library(ggplot2)
```

## Read the original files. 
```{r}
# Import data
setwd("D:/OneDrive - International Campus, Zhejiang University/Projects/Transducing Methods in CAR-T/Data/GSE186596")

# Read data for Patient 1 - Untreated
P1_UT <- Read10X("GSM5657287")
P1_UT <- CreateSeuratObject(counts = P1_UT, min.cells = 3, min.features = 500)
P1_UT$sample_name <- "GSM5657287"
P1_UT$Patient <- "Patient1"
P1_UT$HP <- "Patient"
P1_UT$method <- "Untreated"

# Read data for Patient 1 - LV_CAR
P1_LV_CAR <- Read10X("GSM5657288")
P1_LV_CAR <- CreateSeuratObject(counts = P1_LV_CAR, min.cells = 3, min.features = 500)
P1_LV_CAR$sample_name <- "GSM5657288"
P1_LV_CAR$Patient <- "Patient1"
P1_LV_CAR$HP <- "Patient"
P1_LV_CAR$method <- "LV-19bbz"

# Read data for Patient 1 - LV_CAR_PD1
P1_LV_CAR_PD1 <- Read10X("GSM5657289")
P1_LV_CAR_PD1 <- CreateSeuratObject(counts = P1_LV_CAR_PD1, min.cells = 3, min.features = 500)
P1_LV_CAR_PD1$sample_name <- "GSM5657289"
P1_LV_CAR_PD1$Patient <- "Patient1"
P1_LV_CAR_PD1$HP <- "Patient"
P1_LV_CAR_PD1$method <- "LV-19bbz_PD1-KO"

# Read data for Patient 1 - AAVS1
P1_AAVS1 <- Read10X("GSM5657290")
P1_AAVS1 <- CreateSeuratObject(counts = P1_AAVS1, min.cells = 3, min.features = 500)
P1_AAVS1$sample_name <- "GSM5657290"
P1_AAVS1$Patient <- "Patient1"
P1_AAVS1$HP <- "Patient"
P1_AAVS1$method <- "AAVS1-19bbz"

# Read data for Patient 1 - ET
P1_ET <- Read10X("GSM5657291")
P1_ET <- CreateSeuratObject(counts = P1_ET, min.cells = 3, min.features = 500)
P1_ET$sample_name <- "GSM5657291"
P1_ET$Patient <- "Patient1"
P1_ET$HP <- "Patient"
P1_ET$method <- "PD1-19bbz"
```

```{r}
setwd("D:/OneDrive - International Campus, Zhejiang University/Projects/Transducing Methods in CAR-T/Data/GSE186596")

# Read data for Patient 2 - Untreated
P2_UT <- Read10X("GSM5657292")
P2_UT <- CreateSeuratObject(counts = P2_UT, min.cells = 3, min.features = 500)
P2_UT$sample_name <- "GSM5657292"
P2_UT$Patient <- "Patient2"
P2_UT$HP <- "Patient"
P2_UT$method <- "Untreated"

# Read data for Patient 2 - LV_CAR
P2_LV_CAR <- Read10X("GSM5657293")
P2_LV_CAR <- CreateSeuratObject(counts = P2_LV_CAR, min.cells = 3, min.features = 500)
P2_LV_CAR$sample_name <- "GSM5657293"
P2_LV_CAR$Patient <- "Patient2"
P2_LV_CAR$HP <- "Patient"
P2_LV_CAR$method <- "LV-19bbz"

# Read data for Patient 2 - LV_CAR_PD1
P2_LV_CAR_PD1 <- Read10X("GSM5657294")
P2_LV_CAR_PD1 <- CreateSeuratObject(counts = P2_LV_CAR_PD1, min.cells = 3, min.features = 500)
P2_LV_CAR_PD1$sample_name <- "GSM5657294"
P2_LV_CAR_PD1$Patient <- "Patient2"
P2_LV_CAR_PD1$HP <- "Patient"
P2_LV_CAR_PD1$method <- "LV-19bbz_PD1-KO"

# Read data for Patient 2 - AAVS1
P2_AAVS1 <- Read10X("GSM5657295")
P2_AAVS1 <- CreateSeuratObject(counts = P2_AAVS1, min.cells = 3, min.features = 500)
P2_AAVS1$sample_name <- "GSM5657295"
P2_AAVS1$Patient <- "Patient2"
P2_AAVS1$HP <- "Patient"
P2_AAVS1$method <- "AAVS1-19bbz"

# Read data for Patient 2 - ET
P2_ET <- Read10X("GSM5657296")
P2_ET <- CreateSeuratObject(counts = P2_ET, min.cells = 3, min.features = 500)
P2_ET$sample_name <- "GSM5657296"
P2_ET$Patient <- "Patient2"
P2_ET$HP <- "Patient"
P2_ET$method <- "PD1-19bbz"
```

## Merge
```{r}
# Create a list of Seurat objects
seurat_list <- list(P1_UT, P1_LV_CAR, P1_LV_CAR_PD1, P1_AAVS1, P1_ET, 
                    P2_UT, P2_LV_CAR, P2_LV_CAR_PD1, P2_AAVS1, P2_ET)
# 合并数据集
seurat_object <- merge(P1_UT, y = c(P1_LV_CAR, P1_LV_CAR_PD1, P1_AAVS1, P1_ET, 
                    P2_UT, P2_LV_CAR, P2_LV_CAR_PD1, P2_AAVS1, P2_ET))

# 移除原始数据集
rm(P1_UT, P1_LV_CAR, P1_LV_CAR_PD1, P1_AAVS1, P1_ET, 
                    P2_UT, P2_LV_CAR, P2_LV_CAR_PD1, P2_AAVS1, P2_ET)

rm(seurat_list)
# 保存合并后的结果为RDS文件
setwd("D:/OneDrive - International Campus, Zhejiang University/Projects/Transducing Methods in CAR-T/Data")
saveRDS(seurat_object, file = "CART_Patient.rds")
```

# Preprocess
## QC
```{r}
seurat_object[["percent.mt"]] <- PercentageFeatureSet(seurat_object, pattern = "^MT-|^mt-")
VlnPlot(seurat_object, features = c("nFeature_RNA", "nCount_RNA","percent.mt"), ncol = 2)
seurat_object <- NormalizeData(
  seurat_object, normalization.method = "LogNormalize", scale.factor = 10000)
plot1 <- FeatureScatter(seurat_object, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(seurat_object, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2
```

```{r}
seurat_object <- subset(seurat_object, subset = nFeature_RNA > 200 & nFeature_RNA < 5000 & percent.mt < 20)
seurat_object <- FindVariableFeatures(seurat_object, selection.method = "vst", nfeatures = 2000)
# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(seurat_object), 10)
# plot variable features with and without labels
plot1 =VariableFeaturePlot(seurat_object)
LabelPoints(plot = plot1, points = top10, repel = TRUE)
seurat_object <- ScaleData(seurat_object)
seurat_object <- RunPCA(seurat_object, features = VariableFeatures(object = seurat_object),
                verbose = FALSE)
options(repr.plot.height = 5, repr.plot.width = 12)
```

```{r}
DimPlot(object = seurat_object, reduction = "pca", 
        pt.size = .1, group.by = "method")
VlnPlot(object = seurat_object, features = "PC_1", 
        group.by = "method", pt.size = .1)
DimHeatmap(seurat_object,dims = 1:15, cells = 500, balanced = TRUE)
```

## Harmony
```{r}
library(Rcpp)
library(harmony)

seurat_object <- seurat_object %>% RunHarmony("sample_name",plot_convergence = TRUE,lambda = 10)
harmony_embeddings <- Embeddings(seurat_object, 'harmony')
options(repr.plot.height = 5, repr.plot.width = 12)
DimPlot(object = seurat_object, reduction = "harmony", 
        pt.size = .1, group.by = "sample_name")
VlnPlot(object = seurat_object, features = "harmony_1", 
        group.by = "sample_name", pt.size = .1)

top10 <- head(VariableFeatures(seurat_object), 10)
plot1 = VariableFeaturePlot(seurat_object)
LabelPoints(plot = plot1, points = top10, repel = TRUE)
DimPlot(seurat_object, reduction = "harmony")
DimHeatmap(seurat_object,dims = 1:15, cells = 500, balanced = TRUE)

ElbowPlot(seurat_object)

saveRDS(seurat_object,"CART_Patient_Harmony.rds")
```

## UMAP
```{r}
setwd("D:/OneDrive - International Campus, Zhejiang University/Projects/Lysosome-CART/")
seurat_object <- readRDS("CART_Patient_Harmony.rds")
UMAP <- seurat_object %>% 
  RunUMAP(reduction = "pca", dims = 1:15) %>% 
  FindNeighbors(reduction = "pca", dims = 1:15) %>% 
  FindClusters(resolution =0.8) %>% 
  identity()

DimPlot(UMAP, reduction = "umap", label = TRUE, raster=FALSE)
```

```{r}
setwd("D:/OneDrive - International Campus, Zhejiang University/Projects/Lysosome-CART/")
seurat_object <- readRDS("CART_Patient_Harmony.rds")

TSNE <- seurat_object %>% 
  RunTSNE(reduction = "pca", dims = 1:15) %>% 
  FindNeighbors(reduction = "pca", dims = 1:15) %>% 
  FindClusters(resolution =2.6) %>% 
  identity()

DimPlot(TSNE, reduction = "tsne", label = TRUE, raster=FALSE)
```

```{r}
DimPlot(UMAP, reduction = "umap", group.by = "Patient",repel = TRUE)
DimPlot(UMAP, reduction = "umap", group.by = "sample_name",repel = TRUE)
DimPlot(UMAP, reduction = "umap", group.by = "method",repel = TRUE)

DimPlot(UMAP, reduction = "umap", split.by = "Patient", 
        group.by = "method",repel = TRUE,ncol = 2,pt.size = 0.5)
```

## TSNE
```{r}
DimPlot(TSNE, reduction = "tsne", group.by = "Patient",repel = TRUE)
DimPlot(TSNE, reduction = "tsne", group.by = "sample_name",repel = TRUE)
DimPlot(TSNE, reduction = "tsne", group.by = "method",repel = TRUE)

DimPlot(TSNE, reduction = "tsne", split.by = "Patient", 
        group.by = "method",repel = TRUE,ncol = 2,pt.size = 0.5)
```

# Annonation
## Find Markers
```{r}
library(COSG)
marker_cosg <- cosg(
  TSNE,
  groups='all',
  assay='RNA',
  slot='data',
  mu=1,
  n_genes_user=100)
```

## Cell Type Annonation
```{r}
data <- TSNE
data <- RenameIdents(object = data, "0" = "Naive CD8+ T",
                     "1" = "Naive CD8+ T", 
                     "2" = "Cytotoxic CD4+ T",
                     "3" = "Naive CD4+ T", 
                     "4" = "Naive CD8+ T",
                     '5'='Naive CD4+ T', 
                     '6'= 'Naive CD4+ T',
                     "7" = "Naive CD4+ T", 
                     "8" = "T helper 17", 
                     "9" = "Naive CD8+ T", 
                     "10" = "Central Memory CD8+ T", 
                     "11" = "Regulary T", 
                     "12" = "Exhausted CD8+ T", 
                     "13" = "Naive CD8+ T", 
                     "14" = "Exhausted CD8+ T", 
                     "15" = "Exhausted CD8+ T",
                     "16" = "T helper 17", 
                     "17" = "Regulary T", 
                     "18" = "Exhausted CD8+ T", 
                     "19" = "Exhausted CD8+ T", 
                     "20" = "Exhausted CD8+ T",
                     "21" = "Monocytes", 
                     "22" = "T helper 17",
                     "23" = "T helper 17", 
                     "24" = "Exhausted CD8+ T",
                     '25'='Exhausted CD8+ T', 
                     '26'='Exhausted CD8+ T',
                     "27" = "Exhausted CD8+ T", 
                     "28" = "Effector Memory CD8+ T", 
                     "29" = "Exhausted CD8+ T",
                     "30" = "Naive CD8+ T",
                     "31" = "Naive CD8+ T", 
                     "32" = "Central Memory CD8+ T",
                     "33" = "Exhausted CD8+ T", 
                     "34" = "Central Memory CD8+ T",
                     '35'='Exhausted CD8+ T', 
                     '36'='Naive CD8+ T',
                     "37" = "Regulary T", 
                     "38" = "T helper 17", 
                     "39" = "Exhausted CD8+ T",
                     "40" = "Exhausted CD4+ T", 
                     "41" = "Exhausted CD8+ T",
                     "42" = "Naive CD8+ T",
                     "43" = "Naive CD8+ T", 
                     "44" = "Exhausted CD8+ T", 
                     '45'='Exhausted CD8+ T')

DimPlot(data, reduction = "tsne")
```

## Plot Cell Percentages
```{r}
# 计算各个method中各个细胞亚群的比例
group_counts <- table(data$method, Idents(data))
# 计算各个亚群在每个method中所占的细胞数比例
group_proportions <- prop.table(group_counts, margin = 1)
```

```{r}
#根据orig.ident来计算细胞百分比
cell.prop<-as.data.frame(group_proportions)

write.csv(cell.prop,row.names = FALSE,file = 'cell_prop_all.csv')

allcolour=c("#DC143C","#0000FF","#20B2AA","#FFA500","#9370DB","#98FB98","#F08080","#1E90FF","#7CFC00","#FFFF00",
            "#808000","#FF00FF","#FA8072","#7B68EE","#9400D3","#800080","#A0522D","#D2B48C","#D2691E","#87CEEB","#40E0D0","#5F9EA0",
            "#FF1493","#0000CD","#008B8B","#FFE4B5","#8A2BE2","#228B22","#E9967A","#4682B4","#32CD32","#F0E68C","#FFFFE0","#EE82EE",
            "#FF6347","#6A5ACD","#9932CC","#8B008B","#8B4513","#DEB887")

ggplot(cell.prop) + 
  geom_bar(aes(x =Var2, y= Freq, fill = Var1),stat = "identity",width = 0.7,size = 0.5,colour = '#222222')+ 
  theme_classic() +
  labs(x='Sample',y = 'Ratio')+
  scale_fill_manual(values = allcolour)+
  theme(panel.border = element_rect(fill=NA,color="black", size=0.5, linetype="solid"))
```

```{r}
method_proportions <- t(group_proportions)

write.csv(group_counts,file = 'group_counts.csv')
```

```{r}
DimPlot(TSNE, reduction = "tsne", group.by = "Patient",repel = TRUE)
DimPlot(TSNE, reduction = "tsne", group.by = "sample_name",repel = TRUE)
DimPlot(TSNE, reduction = "tsne", group.by = "method",repel = TRUE)

DimPlot(TSNE, reduction = "tsne", split.by = "Patient", 
        group.by = "method",repel = TRUE,ncol = 2,pt.size = 0.5)
```

# Save
```{r}
saveRDS(TSNE, file = "CART_Patient_TSNE.rds")
```

# Pathway Enrichment
```{r}
library(phangorn)
library(scMetabolism)
library(ggplot2)
library(rsvd)
library(AUCell)
library(GSEABase)
library(GSVA)
```

```{r}
countexp.Seurat<-sc.metabolism.Seurat(obj = TSNE, method = "AUCell", imputation =F, ncores = 2, metabolism.type = "KEGG")
```

```{r}
metabolism.matrix <- countexp.Seurat@assays$METABOLISM$score

row_means <- apply(metabolism.matrix, 1, mean)
sorted_means <- order(row_means, decreasing = TRUE)
top_50_means_rows <- sorted_means[1:40]
common_rows <- intersect(top_20_rows, top_50_means_rows)
common_rows_data <- metabolism.matrix[common_rows, ]

# 计算每行的标准差
row_sd <- apply(common_rows_data, 1, sd)
# 根据标准差对行进行排序
sorted_rows <- order(row_sd, decreasing = TRUE)
# 获取前20个变化最显著的行
top_20_rows <- sorted_rows[1:8]
# 提取原始矩阵中相应的行
top_20_rows_data <- common_rows_data[top_20_rows, ]

input.pathway<- rownames(top_20_rows_data)

DotPlot.metabolism(obj = countexp.Seurat, pathway = input.pathway, phenotype = "method", norm = "y")
```

```{r}
library(dplyr)

top50gene <- diff_UE %>% top_n(n = 50, wt = avg_log2FC) %>% rownames()
bottom50gene <- diff_UE %>% top_n(n = -50, wt = avg_log2FC) %>% rownames()

#构建基因集用于GSVA
mygeneset <- cbind(top50gene,bottom50gene)
mygeneset <- as.data.frame(mygeneset)
```

```{r}
gene.expr <-  as.matrix(TSNE[["RNA"]]@data)

library(GSVA)
gsva.result <- GSVA::gsva(gene.expr, mygeneset,kcdf='Gaussian')

```

```{r}
mymatrix <- t(gsva.result)
mymatrix <- cbind(mymatrix,as.data.frame(pbmc$celltype))
colnames(mymatrix)[ncol(mymatrix)] <- 'CellType'
head(mymatrix)
```

```{r}
library(GSVA)
library(ggplot2)
library(dplyr)
# force = TRUE
library(msigdbr)
library(Seurat)
library(pheatmap)
library(patchwork)

expr <- as.data.frame(TSNE_CD8T@assays$RNA@data) #表达矩阵
meta <- TSNE_CD8T@meta.data[,c("orig.ident","CellType","method")] #类别
m_df = msigdbr(species = "Homo sapiens", category = "C2", subcategory = "CP:KEGG") #选取物种人类
msigdbr_list = split(x = m_df$gene_symbol, f = m_df$gs_name)
expr=as.matrix(expr) 
kegg <- gsva(expr, msigdbr_list, kcdf="Gaussian",method = "gsva",parallel.sz=10) #gsva
pheatmap(kegg, show_rownames=1, show_colnames=0, annotation_col=meta,fontsize_row=5, filename='gsva_heatmap.png', width=15, height=12)#绘制热图
es <- data.frame(t(kegg),stringsAsFactors=F)  #添加到单细胞矩阵中，可视化相关通路的在umap上聚集情况，可理解为一个通路即一个基因
```

```{r}
scRNA <- AddMetaData(TSNE_CD8T, es)

p1 <- FeaturePlot(scRNA, features = "KEGG_PRIMARY_BILE_ACID_BIOSYNTHESIS", reduction = 'tsne')
p2 <- FeaturePlot(scRNA, features = "KEGG_ETHER_LIPID_METABOLISM", reduction = 'tsne')
p3 <- FeaturePlot(scRNA, features = "KEGG_RIBOSOME", reduction = 'tsne')
p4 <- FeaturePlot(scRNA, features = "KEGG_ASTHMA", reduction = 'tsne')

plotc = (p1|p2)/(p3|p4)
```

```{r}
saveRDS(scRNA, file = "CD8T_GSVA.rds")
```

### New analysis
```{r}
library(openxlsx)
scRNA <- readRDS("CART_Transfections_Patient_GSVA.rds")
scRNA$CellType <- Idents(scRNA)
# 定义CellType和method的组合
cell_type_values <- unique(scRNA@meta.data$CellType)
# methods <- c("Untreated", "LV-19bbz", "AAVS1-19bbz", "PD1-19bbz", "LV-19bbz_PD1-KO")

# cell_type <- "Effector Memory CD8+ T"
# method <- "Untreated"

# 循环执行代码并导出结果
for (cell_type in cell_type_values) {
    cell_selection <- subset(scRNA, cells = colnames(scRNA)[scRNA$CellType == cell_type])
    Idents(cell_selection) <- cell_selection$method
    DGE_cell_selection <- FindAllMarkers(cell_selection, logfc.threshold = 0.25)
    
    # save DEG
    result_excel <- createWorkbook()
    clusters <- unique(DGE_cell_selection$cluster)
  for (cluster_val in clusters) {
    subset_data <- DGE_cell_selection[DGE_cell_selection$cluster == cluster_val, ]
    addWorksheet(result_excel, sheetName = as.character(cluster_val))
    writeData(result_excel, sheet = as.character(cluster_val), x = subset_data)
  }
    result_filename <- paste0("DEG_results/", cell_type, "_Transfections_DGE_results.xlsx")
    saveWorkbook(result_excel, result_filename, overwrite = TRUE)
}

# 两两比较
result_excel <- createWorkbook()
for (cell_type in cell_type_values) {
    cell_selection <- subset(scRNA, cells = colnames(scRNA)[scRNA$CellType == cell_type])
    Idents(cell_selection) <- cell_selection$method
    DGE_cell_selection <- FindMarkers(cell_selection, ident.1 = "PD1-19bbz", ident.2 = "LV-19bbz_PD1-KO" , logfc.threshold = 0.25)
    addWorksheet(result_excel, sheetName = cell_type)
    writeData(result_excel, sheet = cell_type, x = DGE_cell_selection, rowNames = TRUE)
}
result_filename <- paste0("DEG_results/", "DEGs", "_LV-ET_DGE_results.xlsx")
saveWorkbook(result_excel, result_filename, overwrite = TRUE)
```

```{r}
features <- c("GZMB", "GNLY", "NKG7", "IL32","CD59",
    "CD27", "SELL", "IL16")
colors <- c("#0072B2","#009E73","#D55E00","#CC79A7","#F0E442",
    "#56B4E9","#E69F00","#00ADA9","#D0E429","#ED008C","#68217A")
p1 <- VlnPlot(scRNA, features, stack = TRUE, split.by = 'method',
    cols = colors, flip = TRUE) +
    theme(legend.position = "bottom")
p1
```











